In [6]:
import numpy as np
np.version.version
#np.__version__

'1.13.3'

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.array([True] * 9).reshape([3, 3])
#np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [18]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [21]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:
arr = np.arange(10)
#out = np.where(arr % 2 == 1, -1, arr)
out = arr.copy()
out[out % 2 == 1] = -1
out, arr

(array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [32]:
np.arange(10).reshape(2, 5)
#np.arange(10).reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.vstack([a, b])
#np.concatenate([a, b], axis=0)
#np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.hstack([a, b])
#np.concatenate([a, b], axis=1)
#np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [43]:
a = np.array([1, 2, 3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])